name: Write Properties
description: Write property to java properties files.
author: Christian Dräger
branding:
  icon: 'edit'
  color: 'yellow'
inputs:
  path:
    description: 'The path to the properties file.'
    required: true
  property:
    description: 'The property you want to write'
    required: true
  value:
    description: 'The properties value you want to write'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.property }}
    - ${{ inputs.value }}
